CREATE DATABASE students_Anirudh;
USE students;

CREATE TABLE STUDENT (
    stdid INT(5),
    stdname VARCHAR(20),
    dob DATE,
    doj DATE,
    fee INT(5),
    gender CHAR(1)
);

-- Q1:
DESC STUDENT;

INSERT INTO STUDENT (stdid, stdname, dob, doj, fee, gender)
VALUES (1, 'SHAREEF', '2001-01-10', '2001-10-05', 10000, 'M');

INSERT INTO STUDENT (stdid, stdname, dob, doj, fee, gender)
VALUES (2, 'NADEEM', '2019-11-03', '2001-10-26', 11000, 'M');

-- Q2:
SELECT * FROM STUDENT;

ALTER TABLE STUDENT ADD PHONE_NO INT(10);

-- Q3:
DESC STUDENT;

ALTER TABLE STUDENT CHANGE COLUMN PHONE_NO STUDENT_NO INT(10);

ALTER TABLE STUDENT RENAME TO STUDENT_INFO;

-- Q4:
SELECT * FROM STUDENT_INFO;

ALTER TABLE STUDENT_INFO DROP COLUMN gender;

-- Q5:
SELECT * FROM STUDENT_INFO;
